// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "termsOfService": "http://swagger.io/terms/",
        "contact": {
            "name": "Sumon Sarker",
            "email": "suman@satcombd.com"
        },
        "license": {
            "name": "Apache 2.0",
            "url": "http://www.apache.org/licenses/LICENSE-2.0.html"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/iservice/employee-list/get-all-employee": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Get All Employee",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Employee Entry Service"
                ],
                "summary": "Get All Employee",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/dto.ResponseDtoV2"
                        }
                    }
                }
            }
        },
        "/iservice/employee/create-one-employee": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Create One Employee",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Employee Entry Service"
                ],
                "summary": "Create One Employee",
                "parameters": [
                    {
                        "description": "Employee ID to get Employee details",
                        "name": "buyer",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/model.EmployeeInfo"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/dto.ResponseDtoV2"
                            }
                        }
                    }
                }
            }
        },
        "/iservice/employee/delete-employee": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Create One Employee",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Employee Entry Service"
                ],
                "summary": "Create One Employee",
                "parameters": [
                    {
                        "description": "Employee ID to get Employee details",
                        "name": "buyer",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dto.DeleteEmployee"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/dto.ResponseDto"
                            }
                        }
                    }
                }
            }
        },
        "/iservice/employee/get-all-employee": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Get All Employee",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Employee Entry Service"
                ],
                "summary": "Get All Employee",
                "parameters": [
                    {
                        "description": "Comp ID to get Employee details",
                        "name": "emp",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dto.CompId"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/dto.ResponseDtoV2"
                        }
                    }
                }
            }
        },
        "/iservice/employee/get-all-employee-by-name": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Get All Employee",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Employee Entry Service"
                ],
                "summary": "Get All Employee",
                "parameters": [
                    {
                        "description": "Comp ID to get Employee details",
                        "name": "emp",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dto.CompId"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/dto.ResponseDtoV2"
                        }
                    }
                }
            }
        },
        "/iservice/employee/get-employee-id": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Get New Employee Id",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Employee Entry Service"
                ],
                "summary": "Get New Employee Id",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/dto.ResponseDtoV2"
                        }
                    }
                }
            }
        },
        "/iservice/employee/get-one-employee": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Get One Employee",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Employee Entry Service"
                ],
                "summary": "Get One Employee",
                "parameters": [
                    {
                        "description": "Employee ID to get Employee details",
                        "name": "buyer",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dto.EmployeeCode"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/dto.ResponseDtoV2"
                            }
                        }
                    }
                }
            }
        },
        "/iservice/employee/update-employee": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Update One Employee",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Employee Entry Service"
                ],
                "summary": "Update One Employee",
                "parameters": [
                    {
                        "description": "Employee ID to get Employee details",
                        "name": "buyer",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dto.UpdateEmployee"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/dto.ResponseDtoV2"
                            }
                        }
                    }
                }
            }
        },
        "/iservice/engineer-list/get-all-engineer": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Get All Engineer",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Engineer Entry Service"
                ],
                "summary": "Get All Engineer",
                "parameters": [
                    {
                        "description": "Comp ID to get Engineer details",
                        "name": "emp",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dto.CompId"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/dto.ResponseDtoV2"
                        }
                    }
                }
            }
        },
        "/iservice/engineer/create-one-engineer": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Create One Engineer",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Engineer Entry Service"
                ],
                "summary": "Create One Engineer",
                "parameters": [
                    {
                        "description": "Engineer ID to get Engineer details",
                        "name": "buyer",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/model.EngineerInfo"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/dto.ResponseDtoV2"
                            }
                        }
                    }
                }
            }
        },
        "/iservice/engineer/delete-engineer": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Create One Engineer",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Engineer Entry Service"
                ],
                "summary": "Create One Engineer",
                "parameters": [
                    {
                        "description": "Engineer ID to get Engineer details",
                        "name": "buyer",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dto.DeleteEngineer"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/dto.ResponseDto"
                            }
                        }
                    }
                }
            }
        },
        "/iservice/engineer/get-all-engineer": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Get All Engineer",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Engineer Entry Service"
                ],
                "summary": "Get All Engineer",
                "parameters": [
                    {
                        "description": "Comp ID to get Engineer details",
                        "name": "emp",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dto.CompId"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/dto.ResponseDtoV2"
                        }
                    }
                }
            }
        },
        "/iservice/engineer/get-all-engineer-by-name": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Get All Engineer",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Engineer Entry Service"
                ],
                "summary": "Get All Engineer",
                "parameters": [
                    {
                        "description": "Comp ID to get Engineer details",
                        "name": "emp",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dto.CompId"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/dto.ResponseDtoV2"
                        }
                    }
                }
            }
        },
        "/iservice/engineer/get-engineer-id": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Get New Engineer Id",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Engineer Entry Service"
                ],
                "summary": "Get New Engineer Id",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/dto.ResponseDtoV2"
                        }
                    }
                }
            }
        },
        "/iservice/engineer/get-one-engineer": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Get One Engineer",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Engineer Entry Service"
                ],
                "summary": "Get One Engineer",
                "parameters": [
                    {
                        "description": "Engineer ID to get Engineer details",
                        "name": "buyer",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dto.EngineerCode"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/dto.ResponseDtoV2"
                            }
                        }
                    }
                }
            }
        },
        "/iservice/engineer/update-engineer": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Update One Engineer",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Engineer Entry Service"
                ],
                "summary": "Update One Engineer",
                "parameters": [
                    {
                        "description": "Engineer ID to get Engineer details",
                        "name": "buyer",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dto.UpdateEngineer"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/dto.ResponseDtoV2"
                            }
                        }
                    }
                }
            }
        },
        "/iservice/serive-party/get-service-party-id": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Get New ServiceParty Id",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "ServiceParty Entry Service"
                ],
                "summary": "Get New ServiceParty Id",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/dto.ResponseDtoV2"
                        }
                    }
                }
            }
        },
        "/iservice/service-party/create-one-service-party": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Create One ServiceParty",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "ServiceParty Entry Service"
                ],
                "summary": "Create One ServiceParty",
                "parameters": [
                    {
                        "description": "ServiceParty ID to get ServiceParty details",
                        "name": "buyer",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/model.ServiceParty"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/dto.ResponseDtoV2"
                            }
                        }
                    }
                }
            }
        },
        "/iservice/service-party/delete-service-party": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Create One ServiceParty",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "ServiceParty Entry Service"
                ],
                "summary": "Create One ServiceParty",
                "parameters": [
                    {
                        "description": "ServiceParty ID to get ServiceParty details",
                        "name": "buyer",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dto.DeleteParty"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/dto.ResponseDto"
                            }
                        }
                    }
                }
            }
        },
        "/iservice/service-party/get-all-service-party": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Get All ServiceParty",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "ServiceParty Entry Service"
                ],
                "summary": "Get All ServiceParty",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/dto.ResponseDtoV2"
                        }
                    }
                }
            }
        },
        "/iservice/service-party/get-all-service-party-by-name": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Get All ServiceParty",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "ServiceParty Entry Service"
                ],
                "summary": "Get All ServiceParty",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/dto.ResponseDtoV2"
                        }
                    }
                }
            }
        },
        "/iservice/service-party/get-one-service-party": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Get One ServiceParty",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "ServiceParty Entry Service"
                ],
                "summary": "Get One ServiceParty",
                "parameters": [
                    {
                        "description": "ServiceParty ID to get ServiceParty details",
                        "name": "buyer",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dto.PartyCode"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/dto.ResponseDtoV2"
                            }
                        }
                    }
                }
            }
        },
        "/iservice/service-party/update-service-party": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Update One ServiceParty",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "ServiceParty Entry Service"
                ],
                "summary": "Update One ServiceParty",
                "parameters": [
                    {
                        "description": "ServiceParty ID to get ServiceParty details",
                        "name": "buyer",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dto.UpdateParty"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/dto.ResponseDtoV2"
                            }
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "dto.CompId": {
            "type": "object",
            "properties": {
                "compid": {
                    "type": "integer"
                }
            }
        },
        "dto.DeleteEmployee": {
            "type": "object",
            "properties": {
                "change_user": {
                    "type": "string"
                },
                "employee_id": {
                    "type": "integer"
                }
            }
        },
        "dto.DeleteEngineer": {
            "type": "object",
            "properties": {
                "change_user": {
                    "type": "string"
                },
                "engineer_id": {
                    "type": "integer"
                }
            }
        },
        "dto.DeleteParty": {
            "type": "object",
            "properties": {
                "change_user": {
                    "type": "string"
                },
                "party_code": {
                    "type": "integer"
                }
            }
        },
        "dto.EmployeeCode": {
            "type": "object",
            "properties": {
                "employee_id": {
                    "type": "integer"
                }
            }
        },
        "dto.EngineerCode": {
            "type": "object",
            "properties": {
                "engineer_id": {
                    "type": "integer"
                }
            }
        },
        "dto.PartyCode": {
            "type": "object",
            "properties": {
                "party_code": {
                    "type": "integer"
                }
            }
        },
        "dto.ResponseDto": {
            "type": "object",
            "properties": {
                "isSuccess": {
                    "type": "boolean"
                },
                "message": {
                    "type": "string"
                },
                "payload": {},
                "statusCode": {
                    "type": "integer"
                }
            }
        },
        "dto.ResponseDtoV2": {
            "type": "object",
            "properties": {
                "data": {},
                "isSuccess": {
                    "type": "boolean"
                },
                "message": {
                    "type": "string"
                },
                "statusCode": {
                    "type": "integer"
                }
            }
        },
        "dto.UpdateEmployee": {
            "type": "object",
            "properties": {
                "change_user": {
                    "type": "string"
                },
                "compid": {
                    "type": "integer"
                },
                "designation": {
                    "type": "string"
                },
                "employee_email": {
                    "type": "string"
                },
                "employee_id": {
                    "type": "integer"
                },
                "employee_name": {
                    "type": "string"
                },
                "employee_phone": {
                    "type": "string"
                }
            }
        },
        "dto.UpdateEngineer": {
            "type": "object",
            "properties": {
                "change_user": {
                    "type": "string"
                },
                "compid": {
                    "type": "integer"
                },
                "designation": {
                    "type": "string"
                },
                "engineer_email": {
                    "type": "string"
                },
                "engineer_id": {
                    "type": "integer"
                },
                "engineer_name": {
                    "type": "string"
                },
                "engineer_phone": {
                    "type": "string"
                }
            }
        },
        "dto.UpdateParty": {
            "type": "object",
            "properties": {
                "change_user": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "party_address": {
                    "type": "string"
                },
                "party_code": {
                    "type": "integer"
                },
                "party_email": {
                    "type": "string"
                },
                "party_name": {
                    "type": "string"
                },
                "party_nid": {
                    "type": "string"
                },
                "party_phone": {
                    "type": "string"
                }
            }
        },
        "model.EmployeeInfo": {
            "type": "object",
            "properties": {
                "compid": {
                    "type": "integer"
                },
                "designation": {
                    "type": "string"
                },
                "employee_email": {
                    "type": "string"
                },
                "employee_id": {
                    "type": "integer"
                },
                "employee_name": {
                    "type": "string"
                },
                "employee_phone": {
                    "type": "string"
                }
            }
        },
        "model.EngineerInfo": {
            "type": "object",
            "properties": {
                "compid": {
                    "type": "integer"
                },
                "designation": {
                    "type": "string"
                },
                "engineer_email": {
                    "type": "string"
                },
                "engineer_id": {
                    "type": "integer"
                },
                "engineer_name": {
                    "type": "string"
                },
                "engineer_phone": {
                    "type": "string"
                }
            }
        },
        "model.ServiceParty": {
            "type": "object",
            "properties": {
                "id": {
                    "type": "integer"
                },
                "party_address": {
                    "type": "string"
                },
                "party_code": {
                    "type": "integer"
                },
                "party_email": {
                    "type": "string"
                },
                "party_name": {
                    "type": "string"
                },
                "party_nid": {
                    "type": "string"
                },
                "party_phone": {
                    "type": "string"
                }
            }
        }
    },
    "securityDefinitions": {
        "BearerAuth": {
            "description": "Type \"Bearer\" followed by a space and JWT token.",
            "type": "apiKey",
            "name": "Authorization",
            "in": "header"
        }
    },
    "externalDocs": {
        "description": "OpenAPI",
        "url": "https://swagger.io/resources/open-api/"
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "2.0",
	Host:             "118.67.213.45:7037",
	BasePath:         "/",
	Schemes:          []string{"http"},
	Title:            "SICL IService API",
	Description:      "An API to perform `SICL IService API` operations. You can find out more about Swagger at [http://swagger.io](http://swagger.io) or on [irc.freenode.net, #swagger](http://swagger.io/irc/).",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
